BEGIN
  -- Удаление таблиц, если существуют
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE demo_orders PURGE';
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
  END;

  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE demo_products PURGE';
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
  END;

  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE demo_customers PURGE';
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
  END;
END;